// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    /**
     * User ID
     */
    user_id: string;
    /**
     * Password
     */
    password: string;
};

export type LoginResponse = {
    status: number;
    data: {
        /**
         * JWT token
         */
        token: string;
        /**
         * Refresh token
         */
        refreshToken: string;
    };
    error: {
        [key: string]: unknown;
    };
};

export type RefreshRequest = {
    /**
     * Refresh token
     */
    refresh_token: string;
};

export type RefreshResponse = {
    status: number;
    data: {
        /**
         * JWT token
         */
        token: string;
        /**
         * Refresh token
         */
        refreshToken: string;
    };
    error: {
        [key: string]: unknown;
    };
};

export type Tag = {
    uuid?: string;
    name?: string;
};

export type Blog = {
    uuid?: string;
    year?: number;
    month?: number;
    day?: number;
    title?: string;
    body?: string;
    is_show?: boolean;
    tags?: Array<Tag>;
    created_at?: string;
    updated_at?: string;
    deleted_at?: string;
};

export type Pagenation = {
    total: number;
    page: number;
    limit: number;
};

export type BlogListResponse = {
    status: number;
    data: {
        blogs: Array<Blog>;
        pagenation: Pagenation;
    };
    error: {
        [key: string]: unknown;
    };
};

export type BlogPostRequest = {
    /**
     * title of the blog post
     */
    title: string;
    /**
     * body of the blog post
     */
    body: string;
    /**
     * whether the blog post is shown or not
     */
    is_show: boolean;
    /**
     * tags of the blog post
     */
    tag_uuids?: Array<(string)>;
};

export type BlogResponse = {
    status: number;
    data: {
        blog?: Blog;
        tags?: Array<Tag>;
    };
    error: {
        [key: string]: unknown;
    };
};

export type BlogUpdateRequest = {
    /**
     * uuid of the blog post
     */
    uuid?: string;
    /**
     * title of the blog post
     */
    title: string;
    /**
     * body of the blog post
     */
    body: string;
    /**
     * whether the blog post is shown or not
     */
    is_show: boolean;
    /**
     * tags of the blog post
     */
    tag_uuids?: Array<(string)>;
};

export type TagListResponse = {
    status: number;
    data: {
        tags: Array<Tag>;
    };
    error: {
        [key: string]: unknown;
    };
};

export type TagCreateRequest = {
    /**
     * Tag name
     */
    name: string;
};

/**
 * Page number
 */
export type ParameterPage = number;

/**
 * Number of items per page
 */
export type ParameterLimit = number;

/**
 * UUID
 */
export type ParameterUuid = string;

/**
 * UUID
 */
export type ParameterQueryUuid = string;

export type LoginData = {
    body: LoginRequest;
};

export type LoginResponse2 = (LoginResponse);

export type LoginError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type LogoutResponse = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        [key: string]: unknown;
    };
});

export type LogoutError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type RefreshTokenData = {
    body: RefreshRequest;
};

export type RefreshTokenResponse = (RefreshResponse);

export type RefreshTokenError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type GetBlogListData = {
    query?: {
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Page number
         */
        page?: number;
    };
};

export type GetBlogListResponse = (BlogListResponse);

export type GetBlogListError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type CreateBlogPostData = {
    body: BlogPostRequest;
};

export type CreateBlogPostResponse = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        [key: string]: unknown;
    };
});

export type CreateBlogPostError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type GetBlogData = {
    path: {
        /**
         * UUID
         */
        uuid: string;
    };
};

export type GetBlogResponse = (BlogResponse);

export type GetBlogError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type UpdateBlogData = {
    body: BlogUpdateRequest;
    path: {
        /**
         * UUID
         */
        uuid: string;
    };
};

export type UpdateBlogResponse = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        [key: string]: unknown;
    };
});

export type UpdateBlogError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type GetTagListData = {
    query?: {
        /**
         * UUID
         */
        uuid?: string;
    };
};

export type GetTagListResponse = (TagListResponse);

export type GetTagListError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type CreateTagData = {
    body: TagCreateRequest;
};

export type CreateTagResponse = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        [key: string]: unknown;
    };
});

export type CreateTagError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});

export type UploadImageData = {
    body: {
        /**
         * image file
         */
        image: (Blob | File);
    };
};

export type UploadImageResponse = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        [key: string]: unknown;
    };
});

export type UploadImageError = ({
    status: number;
    data: {
        [key: string]: unknown;
    };
    error: {
        message?: string;
    };
});